INSERT INTO states(id, name, states_code) VALUES (1, 'Telangana', 'TG'); 
INSERT INTO states(id, name, states_code) VALUES (2, 'Tripura', 'TR'); 
INSERT INTO states(id, name, states_code) VALUES (3, 'Mizoram', 'MZ'); 
INSERT INTO states(id, name, states_code) VALUES (4, 'Andhra Pradesh', 'AP'); 
INSERT INTO states(id, name, states_code) VALUES (5, 'Bihar', 'BR'); 
INSERT INTO states(id, name, states_code) VALUES (6, 'Puducherry', 'PY'); 
INSERT INTO states(id, name, states_code) VALUES (7, 'Tamil Nadu', 'TN'); 
INSERT INTO states(id, name, states_code) VALUES (8, 'Odisha', 'OD'); 
INSERT INTO states(id, name, states_code) VALUES (9, 'Rajasthan', 'RJ'); 
INSERT INTO states(id, name, states_code) VALUES (10, 'Nagaland', 'NL'); 
INSERT INTO states(id, name, states_code) VALUES (11, 'Jammu and Kashmir', 'JK'); 
INSERT INTO states(id, name, states_code) VALUES (12, 'Uttar Pradesh', 'UP'); 
INSERT INTO states(id, name, states_code) VALUES (13, 'Chandigarh', 'CH'); 
INSERT INTO states(id, name, states_code) VALUES (14, 'Kerala', 'KL'); 
INSERT INTO states(id, name, states_code) VALUES (15, 'Karnataka', 'KA'); 
INSERT INTO states(id, name, states_code) VALUES (16, 'Madhya Pradesh', 'MP'); 
INSERT INTO states(id, name, states_code) VALUES (17, 'Haryana', 'HR'); 
INSERT INTO states(id, name, states_code) VALUES (18, 'Punjab', 'PB'); 
INSERT INTO states(id, name, states_code) VALUES (19, 'West Bengal', 'WB'); 
INSERT INTO states(id, name, states_code) VALUES (20, 'Meghalaya', 'ML'); 
INSERT INTO states(id, name, states_code) VALUES (21, 'Manipur', 'MN'); 
INSERT INTO states(id, name, states_code) VALUES (22, 'Dadra and Nagar Haveli and Daman and Diu', 'DN'); 
INSERT INTO states(id, name, states_code) VALUES (23, 'Delhi', 'DL'); 
INSERT INTO states(id, name, states_code) VALUES (24, 'Maharashtra', 'MH'); 
INSERT INTO states(id, name, states_code) VALUES (25, 'Uttarakhand', 'UT'); 
INSERT INTO states(id, name, states_code) VALUES (26, 'Gujarat', 'GJ'); 
INSERT INTO states(id, name, states_code) VALUES (27, 'Himachal Pradesh', 'HP'); 
INSERT INTO states(id, name, states_code) VALUES (28, 'Sikkim', 'SK'); 
INSERT INTO states(id, name, states_code) VALUES (29, 'Chhattisgarh', 'CT'); 
INSERT INTO states(id, name, states_code) VALUES (30, 'Goa', 'GA'); 
INSERT INTO states(id, name, states_code) VALUES (31, 'Arunachal Pradesh', 'AR'); 
INSERT INTO states(id, name, states_code) VALUES (32, 'Jharkhand', 'JH'); 
INSERT INTO states(id, name, states_code) VALUES (33, 'Ladakh', 'LA'); 
INSERT INTO states(id, name, states_code) VALUES (34, 'Assam', 'AS'); 
INSERT INTO states(id, name, states_code) VALUES (35, 'Andaman and Nicobar Islands', 'AN');
INSERT INTO states(id, name, states_code) VALUES (36, 'Lakshadweep', 'LD');
