INSERT INTO districts(id, name, state_id) VALUES (1, 'Nicobars', 35); 
INSERT INTO districts(id, name, state_id) VALUES (2, 'North and Middle Andaman', 35); 
INSERT INTO districts(id, name, state_id) VALUES (3, 'South Andaman', 35); 
INSERT INTO districts(id, name, state_id) VALUES (4, 'Anantapur', 4); 
INSERT INTO districts(id, name, state_id) VALUES (5, 'Chittoor', 4); 
INSERT INTO districts(id, name, state_id) VALUES (6, 'East Godavari', 4); 
INSERT INTO districts(id, name, state_id) VALUES (7, 'Guntur', 4); 
INSERT INTO districts(id, name, state_id) VALUES (8, 'Krishna', 4); 
INSERT INTO districts(id, name, state_id) VALUES (9, 'Kurnool', 4); 
INSERT INTO districts(id, name, state_id) VALUES (10, 'Prakasam', 4); 
INSERT INTO districts(id, name, state_id) VALUES (11, 'S.P.S. Nellore', 4); 
INSERT INTO districts(id, name, state_id) VALUES (12, 'Srikakulam', 4); 
INSERT INTO districts(id, name, state_id) VALUES (13, 'Visakhapatnam', 4); 
INSERT INTO districts(id, name, state_id) VALUES (14, 'Vizianagaram', 4); 
INSERT INTO districts(id, name, state_id) VALUES (15, 'West Godavari', 4); 
INSERT INTO districts(id, name, state_id) VALUES (16, 'Y.S.R. Kadapa', 4); 
INSERT INTO districts(id, name, state_id) VALUES (17, 'Anjaw', 31); 
INSERT INTO districts(id, name, state_id) VALUES (18, 'Changlang', 31); 
INSERT INTO districts(id, name, state_id) VALUES (19, 'East Kameng', 31); 
INSERT INTO districts(id, name, state_id) VALUES (20, 'East Siang', 31); 
INSERT INTO districts(id, name, state_id) VALUES (21, 'Kamle', 31); 
INSERT INTO districts(id, name, state_id) VALUES (22, 'Kra Daadi', 31); 
INSERT INTO districts(id, name, state_id) VALUES (23, 'Kurung Kumey', 31); 
INSERT INTO districts(id, name, state_id) VALUES (24, 'Lepa Rada', 31); 
INSERT INTO districts(id, name, state_id) VALUES (25, 'Lohit', 31); 
INSERT INTO districts(id, name, state_id) VALUES (26, 'Longding', 31); 
INSERT INTO districts(id, name, state_id) VALUES (27, 'Lower Dibang Valley', 31); 
INSERT INTO districts(id, name, state_id) VALUES (28, 'Lower Siang', 31); 
INSERT INTO districts(id, name, state_id) VALUES (29, 'Lower Subansiri', 31); 
INSERT INTO districts(id, name, state_id) VALUES (30, 'Namsai', 31); 
INSERT INTO districts(id, name, state_id) VALUES (31, 'Pakke Kessang', 31); 
INSERT INTO districts(id, name, state_id) VALUES (32, 'Papum Pare', 31); 
INSERT INTO districts(id, name, state_id) VALUES (33, 'Shi Yomi', 31); 
INSERT INTO districts(id, name, state_id) VALUES (34, 'Siang', 31); 
INSERT INTO districts(id, name, state_id) VALUES (35, 'Tawang', 31); 
INSERT INTO districts(id, name, state_id) VALUES (36, 'Tirap', 31); 
INSERT INTO districts(id, name, state_id) VALUES (37, 'Upper Dibang Valley', 31); 
INSERT INTO districts(id, name, state_id) VALUES (38, 'Upper Siang', 31); 
INSERT INTO districts(id, name, state_id) VALUES (39, 'Upper Subansiri', 31); 
INSERT INTO districts(id, name, state_id) VALUES (40, 'West Kameng', 31); 
INSERT INTO districts(id, name, state_id) VALUES (41, 'West Siang', 31); 
INSERT INTO districts(id, name, state_id) VALUES (42, 'Baksa', 34); 
INSERT INTO districts(id, name, state_id) VALUES (43, 'Barpeta', 34); 
INSERT INTO districts(id, name, state_id) VALUES (44, 'Biswanath', 34); 
INSERT INTO districts(id, name, state_id) VALUES (45, 'Bongaigaon', 34); 
INSERT INTO districts(id, name, state_id) VALUES (46, 'Cachar', 34); 
INSERT INTO districts(id, name, state_id) VALUES (47, 'Charaideo', 34); 
INSERT INTO districts(id, name, state_id) VALUES (48, 'Chirang', 34); 
INSERT INTO districts(id, name, state_id) VALUES (49, 'Darrang', 34); 
INSERT INTO districts(id, name, state_id) VALUES (50, 'Dhemaji', 34); 
INSERT INTO districts(id, name, state_id) VALUES (51, 'Dhubri', 34); 
INSERT INTO districts(id, name, state_id) VALUES (52, 'Dibrugarh', 34); 
INSERT INTO districts(id, name, state_id) VALUES (53, 'Dima Hasao', 34); 
INSERT INTO districts(id, name, state_id) VALUES (54, 'Goalpara', 34); 
INSERT INTO districts(id, name, state_id) VALUES (55, 'Golaghat', 34); 
INSERT INTO districts(id, name, state_id) VALUES (56, 'Hailakandi', 34); 
INSERT INTO districts(id, name, state_id) VALUES (57, 'Hojai', 34); 
INSERT INTO districts(id, name, state_id) VALUES (58, 'Jorhat', 34); 
INSERT INTO districts(id, name, state_id) VALUES (59, 'Kamrup', 34); 
INSERT INTO districts(id, name, state_id) VALUES (60, 'Kamrup Metropolitan', 34); 
INSERT INTO districts(id, name, state_id) VALUES (61, 'Karbi Anglong', 34); 
INSERT INTO districts(id, name, state_id) VALUES (62, 'Karimganj', 34); 
INSERT INTO districts(id, name, state_id) VALUES (63, 'Kokrajhar', 34); 
INSERT INTO districts(id, name, state_id) VALUES (64, 'Lakhimpur', 34); 
INSERT INTO districts(id, name, state_id) VALUES (65, 'Majuli', 34); 
INSERT INTO districts(id, name, state_id) VALUES (66, 'Morigaon', 34); 
INSERT INTO districts(id, name, state_id) VALUES (67, 'Nagaon', 34); 
INSERT INTO districts(id, name, state_id) VALUES (68, 'Nalbari', 34); 
INSERT INTO districts(id, name, state_id) VALUES (69, 'Sivasagar', 34); 
INSERT INTO districts(id, name, state_id) VALUES (70, 'Sonitpur', 34); 
INSERT INTO districts(id, name, state_id) VALUES (71, 'South Salmara Mankachar', 34); 
INSERT INTO districts(id, name, state_id) VALUES (72, 'Tinsukia', 34); 
INSERT INTO districts(id, name, state_id) VALUES (73, 'Udalguri', 34); 
INSERT INTO districts(id, name, state_id) VALUES (74, 'West Karbi Anglong', 34); 
INSERT INTO districts(id, name, state_id) VALUES (75, 'Araria', 5); 
INSERT INTO districts(id, name, state_id) VALUES (76, 'Arwal', 5); 
INSERT INTO districts(id, name, state_id) VALUES (77, 'Aurangabad', 5); 
INSERT INTO districts(id, name, state_id) VALUES (78, 'Banka', 5); 
INSERT INTO districts(id, name, state_id) VALUES (79, 'Begusarai', 5); 
INSERT INTO districts(id, name, state_id) VALUES (80, 'Bhagalpur', 5); 
INSERT INTO districts(id, name, state_id) VALUES (81, 'Bhojpur', 5); 
INSERT INTO districts(id, name, state_id) VALUES (82, 'Buxar', 5); 
INSERT INTO districts(id, name, state_id) VALUES (83, 'Darbhanga', 5); 
INSERT INTO districts(id, name, state_id) VALUES (84, 'Gaya', 5); 
INSERT INTO districts(id, name, state_id) VALUES (85, 'Gopalganj', 5); 
INSERT INTO districts(id, name, state_id) VALUES (86, 'Jamui', 5); 
INSERT INTO districts(id, name, state_id) VALUES (87, 'Jehanabad', 5); 
INSERT INTO districts(id, name, state_id) VALUES (88, 'Kaimur', 5); 
INSERT INTO districts(id, name, state_id) VALUES (89, 'Katihar', 5); 
INSERT INTO districts(id, name, state_id) VALUES (90, 'Khagaria', 5); 
INSERT INTO districts(id, name, state_id) VALUES (91, 'Kishanganj', 5); 
INSERT INTO districts(id, name, state_id) VALUES (92, 'Lakhisarai', 5); 
INSERT INTO districts(id, name, state_id) VALUES (93, 'Madhepura', 5); 
INSERT INTO districts(id, name, state_id) VALUES (94, 'Madhubani', 5); 
INSERT INTO districts(id, name, state_id) VALUES (95, 'Munger', 5); 
INSERT INTO districts(id, name, state_id) VALUES (96, 'Muzaffarpur', 5); 
INSERT INTO districts(id, name, state_id) VALUES (97, 'Nalanda', 5); 
INSERT INTO districts(id, name, state_id) VALUES (98, 'Nawada', 5); 
INSERT INTO districts(id, name, state_id) VALUES (99, 'West Champaran', 5); 
INSERT INTO districts(id, name, state_id) VALUES (100, 'Patna', 5); 
INSERT INTO districts(id, name, state_id) VALUES (101, 'East Champaran', 5); 
INSERT INTO districts(id, name, state_id) VALUES (102, 'Purnia', 5); 
INSERT INTO districts(id, name, state_id) VALUES (103, 'Rohtas', 5); 
INSERT INTO districts(id, name, state_id) VALUES (104, 'Saharsa', 5); 
INSERT INTO districts(id, name, state_id) VALUES (105, 'Samastipur', 5); 
INSERT INTO districts(id, name, state_id) VALUES (106, 'Saran', 5); 
INSERT INTO districts(id, name, state_id) VALUES (107, 'Sheikhpura', 5); 
INSERT INTO districts(id, name, state_id) VALUES (108, 'Sheohar', 5); 
INSERT INTO districts(id, name, state_id) VALUES (109, 'Sitamarhi', 5); 
INSERT INTO districts(id, name, state_id) VALUES (110, 'Siwan', 5); 
INSERT INTO districts(id, name, state_id) VALUES (111, 'Supaul', 5); 
INSERT INTO districts(id, name, state_id) VALUES (112, 'Vaishali', 5); 
INSERT INTO districts(id, name, state_id) VALUES (113, 'Chandigarh', 13); 
INSERT INTO districts(id, name, state_id) VALUES (114, 'Balod', 29); 
INSERT INTO districts(id, name, state_id) VALUES (115, 'Baloda Bazar', 29); 
INSERT INTO districts(id, name, state_id) VALUES (116, 'Balrampur', 29); 
INSERT INTO districts(id, name, state_id) VALUES (117, 'Bametara', 29); 
INSERT INTO districts(id, name, state_id) VALUES (118, 'Bastar', 29); 
INSERT INTO districts(id, name, state_id) VALUES (119, 'Bijapur', 29); 
INSERT INTO districts(id, name, state_id) VALUES (120, 'Bilaspur', 29); 
INSERT INTO districts(id, name, state_id) VALUES (121, 'Dakshin Bastar Dantewada', 29); 
INSERT INTO districts(id, name, state_id) VALUES (122, 'Dhamtari', 29); 
INSERT INTO districts(id, name, state_id) VALUES (123, 'Durg', 29); 
INSERT INTO districts(id, name, state_id) VALUES (124, 'Gariaband', 29); 
INSERT INTO districts(id, name, state_id) VALUES (125, 'Janjgir Champa', 29); 
INSERT INTO districts(id, name, state_id) VALUES (126, 'Jashpur', 29); 
INSERT INTO districts(id, name, state_id) VALUES (127, 'Kabeerdham', 29); 
INSERT INTO districts(id, name, state_id) VALUES (128, 'Kondagaon', 29); 
INSERT INTO districts(id, name, state_id) VALUES (129, 'Korba', 29); 
INSERT INTO districts(id, name, state_id) VALUES (130, 'Koriya', 29); 
INSERT INTO districts(id, name, state_id) VALUES (131, 'Mahasamund', 29); 
INSERT INTO districts(id, name, state_id) VALUES (132, 'Mungeli', 29); 
INSERT INTO districts(id, name, state_id) VALUES (133, 'Narayanpur', 29); 
INSERT INTO districts(id, name, state_id) VALUES (134, 'Raigarh', 29); 
INSERT INTO districts(id, name, state_id) VALUES (135, 'Raipur', 29); 
INSERT INTO districts(id, name, state_id) VALUES (136, 'Rajnandgaon', 29); 
INSERT INTO districts(id, name, state_id) VALUES (137, 'Sukma', 29); 
INSERT INTO districts(id, name, state_id) VALUES (138, 'Surajpur', 29); 
INSERT INTO districts(id, name, state_id) VALUES (139, 'Surguja', 29); 
INSERT INTO districts(id, name, state_id) VALUES (140, 'Uttar Bastar Kanker', 29); 
INSERT INTO districts(id, name, state_id) VALUES (141, 'Gaurela Pendra Marwahi', 29); 
INSERT INTO districts(id, name, state_id) VALUES (142, 'Central Delhi', 23); 
INSERT INTO districts(id, name, state_id) VALUES (143, 'East Delhi', 23); 
INSERT INTO districts(id, name, state_id) VALUES (144, 'New Delhi', 23); 
INSERT INTO districts(id, name, state_id) VALUES (145, 'North Delhi', 23); 
INSERT INTO districts(id, name, state_id) VALUES (146, 'North East Delhi', 23); 
INSERT INTO districts(id, name, state_id) VALUES (147, 'North West Delhi', 23); 
INSERT INTO districts(id, name, state_id) VALUES (148, 'Shahdara', 23); 
INSERT INTO districts(id, name, state_id) VALUES (149, 'South Delhi', 23); 
INSERT INTO districts(id, name, state_id) VALUES (150, 'South East Delhi', 23); 
INSERT INTO districts(id, name, state_id) VALUES (151, 'South West Delhi', 23); 
INSERT INTO districts(id, name, state_id) VALUES (152, 'West Delhi', 23); 
INSERT INTO districts(id, name, state_id) VALUES (153, 'Dadra and Nagar Haveli', 22); 
INSERT INTO districts(id, name, state_id) VALUES (154, 'Daman', 22); 
INSERT INTO districts(id, name, state_id) VALUES (155, 'Diu', 22); 
INSERT INTO districts(id, name, state_id) VALUES (156, 'North Goa', 30); 
INSERT INTO districts(id, name, state_id) VALUES (157, 'South Goa', 30); 
INSERT INTO districts(id, name, state_id) VALUES (158, 'Ahmedabad', 26); 
INSERT INTO districts(id, name, state_id) VALUES (159, 'Amreli', 26); 
INSERT INTO districts(id, name, state_id) VALUES (160, 'Anand', 26); 
INSERT INTO districts(id, name, state_id) VALUES (161, 'Aravalli', 26); 
INSERT INTO districts(id, name, state_id) VALUES (162, 'Banaskantha', 26); 
INSERT INTO districts(id, name, state_id) VALUES (163, 'Bharuch', 26); 
INSERT INTO districts(id, name, state_id) VALUES (164, 'Bhavnagar', 26); 
INSERT INTO districts(id, name, state_id) VALUES (165, 'Botad', 26); 
INSERT INTO districts(id, name, state_id) VALUES (166, 'Chhota Udaipur', 26); 
INSERT INTO districts(id, name, state_id) VALUES (167, 'Devbhumi Dwarka', 26); 
INSERT INTO districts(id, name, state_id) VALUES (168, 'Dahod', 26); 
INSERT INTO districts(id, name, state_id) VALUES (169, 'Gandhinagar', 26); 
INSERT INTO districts(id, name, state_id) VALUES (170, 'Gir Somnath', 26); 
INSERT INTO districts(id, name, state_id) VALUES (171, 'Jamnagar', 26); 
INSERT INTO districts(id, name, state_id) VALUES (172, 'Junagadh', 26); 
INSERT INTO districts(id, name, state_id) VALUES (173, 'Kutch', 26); 
INSERT INTO districts(id, name, state_id) VALUES (174, 'Kheda', 26); 
INSERT INTO districts(id, name, state_id) VALUES (175, 'Mehsana', 26); 
INSERT INTO districts(id, name, state_id) VALUES (176, 'Mahisagar', 26); 
INSERT INTO districts(id, name, state_id) VALUES (177, 'Morbi', 26); 
INSERT INTO districts(id, name, state_id) VALUES (178, 'Narmada', 26); 
INSERT INTO districts(id, name, state_id) VALUES (179, 'Navsari', 26); 
INSERT INTO districts(id, name, state_id) VALUES (180, 'Panchmahal', 26); 
INSERT INTO districts(id, name, state_id) VALUES (181, 'Patan', 26); 
INSERT INTO districts(id, name, state_id) VALUES (182, 'Porbandar', 26); 
INSERT INTO districts(id, name, state_id) VALUES (183, 'Rajkot', 26); 
INSERT INTO districts(id, name, state_id) VALUES (184, 'Sabarkantha', 26); 
INSERT INTO districts(id, name, state_id) VALUES (185, 'Surat', 26); 
INSERT INTO districts(id, name, state_id) VALUES (186, 'Surendranagar', 26); 
INSERT INTO districts(id, name, state_id) VALUES (187, 'Tapi', 26); 
INSERT INTO districts(id, name, state_id) VALUES (188, 'Dang', 26); 
INSERT INTO districts(id, name, state_id) VALUES (189, 'Vadodara', 26); 
INSERT INTO districts(id, name, state_id) VALUES (190, 'Valsad', 26); 
INSERT INTO districts(id, name, state_id) VALUES (191, 'Bilaspur', 27); 
INSERT INTO districts(id, name, state_id) VALUES (192, 'Chamba', 27); 
INSERT INTO districts(id, name, state_id) VALUES (193, 'Hamirpur', 27); 
INSERT INTO districts(id, name, state_id) VALUES (194, 'Kangra', 27); 
INSERT INTO districts(id, name, state_id) VALUES (195, 'Kinnaur', 27); 
INSERT INTO districts(id, name, state_id) VALUES (196, 'Kullu', 27); 
INSERT INTO districts(id, name, state_id) VALUES (197, 'Lahaul and Spiti', 27); 
INSERT INTO districts(id, name, state_id) VALUES (198, 'Mandi', 27); 
INSERT INTO districts(id, name, state_id) VALUES (199, 'Shimla', 27); 
INSERT INTO districts(id, name, state_id) VALUES (200, 'Sirmaur', 27); 
INSERT INTO districts(id, name, state_id) VALUES (201, 'Solan', 27); 
INSERT INTO districts(id, name, state_id) VALUES (202, 'Una', 27); 
INSERT INTO districts(id, name, state_id) VALUES (203, 'Ambala', 17); 
INSERT INTO districts(id, name, state_id) VALUES (204, 'Bhiwani', 17); 
INSERT INTO districts(id, name, state_id) VALUES (205, 'Charkhi Dadri', 17); 
INSERT INTO districts(id, name, state_id) VALUES (206, 'Faridabad', 17); 
INSERT INTO districts(id, name, state_id) VALUES (207, 'Fatehabad', 17); 
INSERT INTO districts(id, name, state_id) VALUES (208, 'Gurugram', 17); 
INSERT INTO districts(id, name, state_id) VALUES (209, 'Hisar', 17); 
INSERT INTO districts(id, name, state_id) VALUES (210, 'Jhajjar', 17); 
INSERT INTO districts(id, name, state_id) VALUES (211, 'Jind', 17); 
INSERT INTO districts(id, name, state_id) VALUES (212, 'Kaithal', 17); 
INSERT INTO districts(id, name, state_id) VALUES (213, 'Karnal', 17); 
INSERT INTO districts(id, name, state_id) VALUES (214, 'Kurukshetra', 17); 
INSERT INTO districts(id, name, state_id) VALUES (215, 'Mahendragarh', 17); 
INSERT INTO districts(id, name, state_id) VALUES (216, 'Nuh', 17); 
INSERT INTO districts(id, name, state_id) VALUES (217, 'Palwal', 17); 
INSERT INTO districts(id, name, state_id) VALUES (218, 'Panchkula', 17); 
INSERT INTO districts(id, name, state_id) VALUES (219, 'Panipat', 17); 
INSERT INTO districts(id, name, state_id) VALUES (220, 'Rewari', 17); 
INSERT INTO districts(id, name, state_id) VALUES (221, 'Rohtak', 17); 
INSERT INTO districts(id, name, state_id) VALUES (222, 'Sirsa', 17); 
INSERT INTO districts(id, name, state_id) VALUES (223, 'Sonipat', 17); 
INSERT INTO districts(id, name, state_id) VALUES (224, 'Yamunanagar', 17); 
INSERT INTO districts(id, name, state_id) VALUES (225, 'Bokaro', 32); 
INSERT INTO districts(id, name, state_id) VALUES (226, 'Chatra', 32); 
INSERT INTO districts(id, name, state_id) VALUES (227, 'Deoghar', 32); 
INSERT INTO districts(id, name, state_id) VALUES (228, 'Dhanbad', 32); 
INSERT INTO districts(id, name, state_id) VALUES (229, 'Dumka', 32); 
INSERT INTO districts(id, name, state_id) VALUES (230, 'Garhwa', 32); 
INSERT INTO districts(id, name, state_id) VALUES (231, 'Giridih', 32); 
INSERT INTO districts(id, name, state_id) VALUES (232, 'Godda', 32); 
INSERT INTO districts(id, name, state_id) VALUES (233, 'Gumla', 32); 
INSERT INTO districts(id, name, state_id) VALUES (234, 'Hazaribagh', 32); 
INSERT INTO districts(id, name, state_id) VALUES (235, 'Jamtara', 32); 
INSERT INTO districts(id, name, state_id) VALUES (236, 'Khunti', 32); 
INSERT INTO districts(id, name, state_id) VALUES (237, 'Koderma', 32); 
INSERT INTO districts(id, name, state_id) VALUES (238, 'Latehar', 32); 
INSERT INTO districts(id, name, state_id) VALUES (239, 'Lohardaga', 32); 
INSERT INTO districts(id, name, state_id) VALUES (240, 'Pakur', 32); 
INSERT INTO districts(id, name, state_id) VALUES (241, 'Palamu', 32); 
INSERT INTO districts(id, name, state_id) VALUES (242, 'West Singhbhum', 32); 
INSERT INTO districts(id, name, state_id) VALUES (243, 'East Singhbhum', 32); 
INSERT INTO districts(id, name, state_id) VALUES (244, 'Ramgarh', 32); 
INSERT INTO districts(id, name, state_id) VALUES (245, 'Ranchi', 32); 
INSERT INTO districts(id, name, state_id) VALUES (246, 'Sahibganj', 32); 
INSERT INTO districts(id, name, state_id) VALUES (247, 'Saraikela-Kharsawan', 32); 
INSERT INTO districts(id, name, state_id) VALUES (248, 'Simdega', 32); 
INSERT INTO districts(id, name, state_id) VALUES (249, 'Anantnag', 11); 
INSERT INTO districts(id, name, state_id) VALUES (250, 'Budgam', 11); 
INSERT INTO districts(id, name, state_id) VALUES (251, 'Bandipora', 11); 
INSERT INTO districts(id, name, state_id) VALUES (252, 'Baramulla', 11); 
INSERT INTO districts(id, name, state_id) VALUES (253, 'Doda', 11); 
INSERT INTO districts(id, name, state_id) VALUES (254, 'Ganderbal', 11); 
INSERT INTO districts(id, name, state_id) VALUES (255, 'Jammu', 11); 
INSERT INTO districts(id, name, state_id) VALUES (256, 'Kathua', 11); 
INSERT INTO districts(id, name, state_id) VALUES (257, 'Kishtwar', 11); 
INSERT INTO districts(id, name, state_id) VALUES (258, 'Kulgam', 11); 
INSERT INTO districts(id, name, state_id) VALUES (259, 'Kupwara', 11); 
INSERT INTO districts(id, name, state_id) VALUES (260, 'Mirpur', 11); 
INSERT INTO districts(id, name, state_id) VALUES (261, 'Muzaffarabad', 11); 
INSERT INTO districts(id, name, state_id) VALUES (262, 'Pulwama', 11); 
INSERT INTO districts(id, name, state_id) VALUES (263, 'Punch', 11); 
INSERT INTO districts(id, name, state_id) VALUES (264, 'Rajouri', 11); 
INSERT INTO districts(id, name, state_id) VALUES (265, 'Ramban', 11); 
INSERT INTO districts(id, name, state_id) VALUES (266, 'Reasi', 11); 
INSERT INTO districts(id, name, state_id) VALUES (267, 'Samba', 11); 
INSERT INTO districts(id, name, state_id) VALUES (268, 'Shopiyan', 11); 
INSERT INTO districts(id, name, state_id) VALUES (269, 'Srinagar', 11); 
INSERT INTO districts(id, name, state_id) VALUES (270, 'Udhampur', 11); 
INSERT INTO districts(id, name, state_id) VALUES (271, 'Bagalkote', 15); 
INSERT INTO districts(id, name, state_id) VALUES (272, 'Ballari', 15); 
INSERT INTO districts(id, name, state_id) VALUES (273, 'Belagavi', 15); 
INSERT INTO districts(id, name, state_id) VALUES (274, 'Bengaluru Urban', 15); 
INSERT INTO districts(id, name, state_id) VALUES (275, 'Bengaluru Rural', 15); 
INSERT INTO districts(id, name, state_id) VALUES (276, 'Bidar', 15); 
INSERT INTO districts(id, name, state_id) VALUES (277, 'Chamarajanagara', 15); 
INSERT INTO districts(id, name, state_id) VALUES (278, 'Chikkaballapura', 15); 
INSERT INTO districts(id, name, state_id) VALUES (279, 'Chikkamagaluru', 15); 
INSERT INTO districts(id, name, state_id) VALUES (280, 'Chitradurga', 15); 
INSERT INTO districts(id, name, state_id) VALUES (281, 'Dakshina Kannada', 15); 
INSERT INTO districts(id, name, state_id) VALUES (282, 'Davanagere', 15); 
INSERT INTO districts(id, name, state_id) VALUES (283, 'Dharwad', 15); 
INSERT INTO districts(id, name, state_id) VALUES (284, 'Gadag', 15); 
INSERT INTO districts(id, name, state_id) VALUES (285, 'Hassan', 15); 
INSERT INTO districts(id, name, state_id) VALUES (286, 'Haveri', 15); 
INSERT INTO districts(id, name, state_id) VALUES (287, 'Kalaburagi', 15); 
INSERT INTO districts(id, name, state_id) VALUES (288, 'Kodagu', 15); 
INSERT INTO districts(id, name, state_id) VALUES (289, 'Kolar', 15); 
INSERT INTO districts(id, name, state_id) VALUES (290, 'Koppal', 15); 
INSERT INTO districts(id, name, state_id) VALUES (291, 'Mandya', 15); 
INSERT INTO districts(id, name, state_id) VALUES (292, 'Mysuru', 15); 
INSERT INTO districts(id, name, state_id) VALUES (293, 'Raichur', 15); 
INSERT INTO districts(id, name, state_id) VALUES (294, 'Ramanagara', 15); 
INSERT INTO districts(id, name, state_id) VALUES (295, 'Shivamogga', 15); 
INSERT INTO districts(id, name, state_id) VALUES (296, 'Tumakuru', 15); 
INSERT INTO districts(id, name, state_id) VALUES (297, 'Udupi', 15); 
INSERT INTO districts(id, name, state_id) VALUES (298, 'Uttara Kannada', 15); 
INSERT INTO districts(id, name, state_id) VALUES (299, 'Vijayapura', 15); 
INSERT INTO districts(id, name, state_id) VALUES (300, 'Yadgir', 15); 
INSERT INTO districts(id, name, state_id) VALUES (301, 'Alappuzha', 14); 
INSERT INTO districts(id, name, state_id) VALUES (302, 'Ernakulam', 14); 
INSERT INTO districts(id, name, state_id) VALUES (303, 'Idukki', 14); 
INSERT INTO districts(id, name, state_id) VALUES (304, 'Kannur', 14); 
INSERT INTO districts(id, name, state_id) VALUES (305, 'Kasaragod', 14); 
INSERT INTO districts(id, name, state_id) VALUES (306, 'Kollam', 14); 
INSERT INTO districts(id, name, state_id) VALUES (307, 'Kottayam', 14); 
INSERT INTO districts(id, name, state_id) VALUES (308, 'Kozhikode', 14); 
INSERT INTO districts(id, name, state_id) VALUES (309, 'Malappuram', 14); 
INSERT INTO districts(id, name, state_id) VALUES (310, 'Palakkad', 14); 
INSERT INTO districts(id, name, state_id) VALUES (311, 'Pathanamthitta', 14); 
INSERT INTO districts(id, name, state_id) VALUES (312, 'Thiruvananthapuram', 14); 
INSERT INTO districts(id, name, state_id) VALUES (313, 'Thrissur', 14); 
INSERT INTO districts(id, name, state_id) VALUES (314, 'Wayanad', 14); 
INSERT INTO districts(id, name, state_id) VALUES (315, 'Kargil', 33); 
INSERT INTO districts(id, name, state_id) VALUES (316, 'Leh', 33); 
INSERT INTO districts(id, name, state_id) VALUES (317, 'Lakshadweep', 36); 
INSERT INTO districts(id, name, state_id) VALUES (318, 'Ahmednagar', 24); 
INSERT INTO districts(id, name, state_id) VALUES (319, 'Akola', 24); 
INSERT INTO districts(id, name, state_id) VALUES (320, 'Amravati', 24); 
INSERT INTO districts(id, name, state_id) VALUES (321, 'Aurangabad', 24); 
INSERT INTO districts(id, name, state_id) VALUES (322, 'Bhandara', 24); 
INSERT INTO districts(id, name, state_id) VALUES (323, 'Beed', 24); 
INSERT INTO districts(id, name, state_id) VALUES (324, 'Buldhana', 24); 
INSERT INTO districts(id, name, state_id) VALUES (325, 'Chandrapur', 24); 
INSERT INTO districts(id, name, state_id) VALUES (326, 'Dhule', 24); 
INSERT INTO districts(id, name, state_id) VALUES (327, 'Gadchiroli', 24); 
INSERT INTO districts(id, name, state_id) VALUES (328, 'Gondia', 24); 
INSERT INTO districts(id, name, state_id) VALUES (329, 'Hingoli', 24); 
INSERT INTO districts(id, name, state_id) VALUES (330, 'Jalgaon', 24); 
INSERT INTO districts(id, name, state_id) VALUES (331, 'Jalna', 24); 
INSERT INTO districts(id, name, state_id) VALUES (332, 'Kolhapur', 24); 
INSERT INTO districts(id, name, state_id) VALUES (333, 'Latur', 24); 
INSERT INTO districts(id, name, state_id) VALUES (334, 'Mumbai', 24); 
INSERT INTO districts(id, name, state_id) VALUES (335, 'Mumbai Suburban', 24); 
INSERT INTO districts(id, name, state_id) VALUES (336, 'Nagpur', 24); 
INSERT INTO districts(id, name, state_id) VALUES (337, 'Nanded', 24); 
INSERT INTO districts(id, name, state_id) VALUES (338, 'Nandurbar', 24); 
INSERT INTO districts(id, name, state_id) VALUES (339, 'Nashik', 24); 
INSERT INTO districts(id, name, state_id) VALUES (340, 'Osmanabad', 24); 
INSERT INTO districts(id, name, state_id) VALUES (341, 'Palghar', 24); 
INSERT INTO districts(id, name, state_id) VALUES (342, 'Parbhani', 24); 
INSERT INTO districts(id, name, state_id) VALUES (343, 'Pune', 24); 
INSERT INTO districts(id, name, state_id) VALUES (344, 'Raigad', 24); 
INSERT INTO districts(id, name, state_id) VALUES (345, 'Ratnagiri', 24); 
INSERT INTO districts(id, name, state_id) VALUES (346, 'Sangli', 24); 
INSERT INTO districts(id, name, state_id) VALUES (347, 'Satara', 24); 
INSERT INTO districts(id, name, state_id) VALUES (348, 'Sindhudurg', 24); 
INSERT INTO districts(id, name, state_id) VALUES (349, 'Solapur', 24); 
INSERT INTO districts(id, name, state_id) VALUES (350, 'Thane', 24); 
INSERT INTO districts(id, name, state_id) VALUES (351, 'Wardha', 24); 
INSERT INTO districts(id, name, state_id) VALUES (352, 'Washim', 24); 
INSERT INTO districts(id, name, state_id) VALUES (353, 'Yavatmal', 24); 
INSERT INTO districts(id, name, state_id) VALUES (354, 'East Garo Hills', 20); 
INSERT INTO districts(id, name, state_id) VALUES (355, 'East Jaintia Hills', 20); 
INSERT INTO districts(id, name, state_id) VALUES (356, 'East Khasi Hills', 20); 
INSERT INTO districts(id, name, state_id) VALUES (357, 'North Garo Hills', 20); 
INSERT INTO districts(id, name, state_id) VALUES (358, 'Ribhoi', 20); 
INSERT INTO districts(id, name, state_id) VALUES (359, 'South Garo Hills', 20); 
INSERT INTO districts(id, name, state_id) VALUES (360, 'South West Garo Hills', 20); 
INSERT INTO districts(id, name, state_id) VALUES (361, 'South West Khasi Hills', 20); 
INSERT INTO districts(id, name, state_id) VALUES (362, 'West Garo Hills', 20); 
INSERT INTO districts(id, name, state_id) VALUES (363, 'West Jaintia Hills', 20); 
INSERT INTO districts(id, name, state_id) VALUES (364, 'West Khasi Hills', 20); 
INSERT INTO districts(id, name, state_id) VALUES (365, 'Bishnupur', 21); 
INSERT INTO districts(id, name, state_id) VALUES (366, 'Chandel', 21); 
INSERT INTO districts(id, name, state_id) VALUES (367, 'Churachandpur', 21); 
INSERT INTO districts(id, name, state_id) VALUES (368, 'Imphal East', 21); 
INSERT INTO districts(id, name, state_id) VALUES (369, 'Imphal West', 21); 
INSERT INTO districts(id, name, state_id) VALUES (370, 'Jiribam', 21); 
INSERT INTO districts(id, name, state_id) VALUES (371, 'Kakching', 21); 
INSERT INTO districts(id, name, state_id) VALUES (372, 'Kamjong', 21); 
INSERT INTO districts(id, name, state_id) VALUES (373, 'Kangpokpi', 21); 
INSERT INTO districts(id, name, state_id) VALUES (374, 'Noney', 21); 
INSERT INTO districts(id, name, state_id) VALUES (375, 'Pherzawl', 21); 
INSERT INTO districts(id, name, state_id) VALUES (376, 'Senapati', 21); 
INSERT INTO districts(id, name, state_id) VALUES (377, 'Tamenglong', 21); 
INSERT INTO districts(id, name, state_id) VALUES (378, 'Tengnoupal', 21); 
INSERT INTO districts(id, name, state_id) VALUES (379, 'Thoubal', 21); 
INSERT INTO districts(id, name, state_id) VALUES (380, 'Ukhrul', 21); 
INSERT INTO districts(id, name, state_id) VALUES (381, 'Agar Malwa', 16); 
INSERT INTO districts(id, name, state_id) VALUES (382, 'Alirajpur', 16); 
INSERT INTO districts(id, name, state_id) VALUES (383, 'Anuppur', 16); 
INSERT INTO districts(id, name, state_id) VALUES (384, 'Ashoknagar', 16); 
INSERT INTO districts(id, name, state_id) VALUES (385, 'Balaghat', 16); 
INSERT INTO districts(id, name, state_id) VALUES (386, 'Barwani', 16); 
INSERT INTO districts(id, name, state_id) VALUES (387, 'Betul', 16); 
INSERT INTO districts(id, name, state_id) VALUES (388, 'Bhind', 16); 
INSERT INTO districts(id, name, state_id) VALUES (389, 'Bhopal', 16); 
INSERT INTO districts(id, name, state_id) VALUES (390, 'Burhanpur', 16); 
INSERT INTO districts(id, name, state_id) VALUES (391, 'Chhatarpur', 16); 
INSERT INTO districts(id, name, state_id) VALUES (392, 'Chhindwara', 16); 
INSERT INTO districts(id, name, state_id) VALUES (393, 'Damoh', 16); 
INSERT INTO districts(id, name, state_id) VALUES (394, 'Datia', 16); 
INSERT INTO districts(id, name, state_id) VALUES (395, 'Dewas', 16); 
INSERT INTO districts(id, name, state_id) VALUES (396, 'Dhar', 16); 
INSERT INTO districts(id, name, state_id) VALUES (397, 'Dindori', 16); 
INSERT INTO districts(id, name, state_id) VALUES (398, 'Khandwa', 16); 
INSERT INTO districts(id, name, state_id) VALUES (399, 'Guna', 16); 
INSERT INTO districts(id, name, state_id) VALUES (400, 'Gwalior', 16); 
INSERT INTO districts(id, name, state_id) VALUES (401, 'Harda', 16); 
INSERT INTO districts(id, name, state_id) VALUES (402, 'Hoshangabad', 16); 
INSERT INTO districts(id, name, state_id) VALUES (403, 'Indore', 16); 
INSERT INTO districts(id, name, state_id) VALUES (404, 'Jabalpur', 16); 
INSERT INTO districts(id, name, state_id) VALUES (405, 'Jhabua', 16); 
INSERT INTO districts(id, name, state_id) VALUES (406, 'Katni', 16); 
INSERT INTO districts(id, name, state_id) VALUES (407, 'Mandla', 16); 
INSERT INTO districts(id, name, state_id) VALUES (408, 'Mandsaur', 16); 
INSERT INTO districts(id, name, state_id) VALUES (409, 'Morena', 16); 
INSERT INTO districts(id, name, state_id) VALUES (410, 'Narsinghpur', 16); 
INSERT INTO districts(id, name, state_id) VALUES (411, 'Neemuch', 16); 
INSERT INTO districts(id, name, state_id) VALUES (412, 'Niwari', 16); 
INSERT INTO districts(id, name, state_id) VALUES (413, 'Panna', 16); 
INSERT INTO districts(id, name, state_id) VALUES (414, 'Raisen', 16); 
INSERT INTO districts(id, name, state_id) VALUES (415, 'Rajgarh', 16); 
INSERT INTO districts(id, name, state_id) VALUES (416, 'Ratlam', 16); 
INSERT INTO districts(id, name, state_id) VALUES (417, 'Rewa', 16); 
INSERT INTO districts(id, name, state_id) VALUES (418, 'Sagar', 16); 
INSERT INTO districts(id, name, state_id) VALUES (419, 'Satna', 16); 
INSERT INTO districts(id, name, state_id) VALUES (420, 'Sehore', 16); 
INSERT INTO districts(id, name, state_id) VALUES (421, 'Seoni', 16); 
INSERT INTO districts(id, name, state_id) VALUES (422, 'Shahdol', 16); 
INSERT INTO districts(id, name, state_id) VALUES (423, 'Shajapur', 16); 
INSERT INTO districts(id, name, state_id) VALUES (424, 'Sheopur', 16); 
INSERT INTO districts(id, name, state_id) VALUES (425, 'Shivpuri', 16); 
INSERT INTO districts(id, name, state_id) VALUES (426, 'Sidhi', 16); 
INSERT INTO districts(id, name, state_id) VALUES (427, 'Singrauli', 16); 
INSERT INTO districts(id, name, state_id) VALUES (428, 'Tikamgarh', 16); 
INSERT INTO districts(id, name, state_id) VALUES (429, 'Ujjain', 16); 
INSERT INTO districts(id, name, state_id) VALUES (430, 'Umaria', 16); 
INSERT INTO districts(id, name, state_id) VALUES (431, 'Vidisha', 16); 
INSERT INTO districts(id, name, state_id) VALUES (432, 'Khargone', 16); 
INSERT INTO districts(id, name, state_id) VALUES (433, 'Aizawl', 3); 
INSERT INTO districts(id, name, state_id) VALUES (434, 'Champhai', 3); 
INSERT INTO districts(id, name, state_id) VALUES (435, 'Kolasib', 3); 
INSERT INTO districts(id, name, state_id) VALUES (436, 'Lawngtlai', 3); 
INSERT INTO districts(id, name, state_id) VALUES (437, 'Lunglei', 3); 
INSERT INTO districts(id, name, state_id) VALUES (438, 'Mamit', 3); 
INSERT INTO districts(id, name, state_id) VALUES (439, 'Saiha', 3); 
INSERT INTO districts(id, name, state_id) VALUES (440, 'Serchhip', 3); 
INSERT INTO districts(id, name, state_id) VALUES (441, 'Saitual', 3); 
INSERT INTO districts(id, name, state_id) VALUES (442, 'Hnahthial', 3); 
INSERT INTO districts(id, name, state_id) VALUES (443, 'Khawzawl', 3); 
INSERT INTO districts(id, name, state_id) VALUES (444, 'Dimapur', 10); 
INSERT INTO districts(id, name, state_id) VALUES (445, 'Kiphire', 10); 
INSERT INTO districts(id, name, state_id) VALUES (446, 'Kohima', 10); 
INSERT INTO districts(id, name, state_id) VALUES (447, 'Longleng', 10); 
INSERT INTO districts(id, name, state_id) VALUES (448, 'Mokokchung', 10); 
INSERT INTO districts(id, name, state_id) VALUES (449, 'Mon', 10); 
INSERT INTO districts(id, name, state_id) VALUES (450, 'Peren', 10); 
INSERT INTO districts(id, name, state_id) VALUES (451, 'Phek', 10); 
INSERT INTO districts(id, name, state_id) VALUES (452, 'Tuensang', 10); 
INSERT INTO districts(id, name, state_id) VALUES (453, 'Wokha', 10); 
INSERT INTO districts(id, name, state_id) VALUES (454, 'Zunheboto', 10); 
INSERT INTO districts(id, name, state_id) VALUES (455, 'Angul', 8); 
INSERT INTO districts(id, name, state_id) VALUES (456, 'Balangir', 8); 
INSERT INTO districts(id, name, state_id) VALUES (457, 'Balasore', 8); 
INSERT INTO districts(id, name, state_id) VALUES (458, 'Bargarh', 8); 
INSERT INTO districts(id, name, state_id) VALUES (459, 'Boudh', 8); 
INSERT INTO districts(id, name, state_id) VALUES (460, 'Bhadrak', 8); 
INSERT INTO districts(id, name, state_id) VALUES (461, 'Cuttack', 8); 
INSERT INTO districts(id, name, state_id) VALUES (462, 'Deogarh', 8); 
INSERT INTO districts(id, name, state_id) VALUES (463, 'Dhenkanal', 8); 
INSERT INTO districts(id, name, state_id) VALUES (464, 'Gajapati', 8); 
INSERT INTO districts(id, name, state_id) VALUES (465, 'Ganjam', 8); 
INSERT INTO districts(id, name, state_id) VALUES (466, 'Jagatsinghpur', 8); 
INSERT INTO districts(id, name, state_id) VALUES (467, 'Jajpur', 8); 
INSERT INTO districts(id, name, state_id) VALUES (468, 'Jharsuguda', 8); 
INSERT INTO districts(id, name, state_id) VALUES (469, 'Kalahandi', 8); 
INSERT INTO districts(id, name, state_id) VALUES (470, 'Kandhamal', 8); 
INSERT INTO districts(id, name, state_id) VALUES (471, 'Kendrapara', 8); 
INSERT INTO districts(id, name, state_id) VALUES (472, 'Kendujhar', 8); 
INSERT INTO districts(id, name, state_id) VALUES (473, 'Khordha', 8); 
INSERT INTO districts(id, name, state_id) VALUES (474, 'Koraput', 8); 
INSERT INTO districts(id, name, state_id) VALUES (475, 'Malkangiri', 8); 
INSERT INTO districts(id, name, state_id) VALUES (476, 'Mayurbhanj', 8); 
INSERT INTO districts(id, name, state_id) VALUES (477, 'Nabarangapur', 8); 
INSERT INTO districts(id, name, state_id) VALUES (478, 'Nayagarh', 8); 
INSERT INTO districts(id, name, state_id) VALUES (479, 'Nuapada', 8); 
INSERT INTO districts(id, name, state_id) VALUES (480, 'Puri', 8); 
INSERT INTO districts(id, name, state_id) VALUES (481, 'Rayagada', 8); 
INSERT INTO districts(id, name, state_id) VALUES (482, 'Sambalpur', 8); 
INSERT INTO districts(id, name, state_id) VALUES (483, 'Subarnapur', 8); 
INSERT INTO districts(id, name, state_id) VALUES (484, 'Sundargarh', 8); 
INSERT INTO districts(id, name, state_id) VALUES (485, 'Amritsar', 18); 
INSERT INTO districts(id, name, state_id) VALUES (486, 'Barnala', 18); 
INSERT INTO districts(id, name, state_id) VALUES (487, 'Bathinda', 18); 
INSERT INTO districts(id, name, state_id) VALUES (488, 'Faridkot', 18); 
INSERT INTO districts(id, name, state_id) VALUES (489, 'Fatehgarh Sahib', 18); 
INSERT INTO districts(id, name, state_id) VALUES (490, 'Fazilka', 18); 
INSERT INTO districts(id, name, state_id) VALUES (491, 'Ferozepur', 18); 
INSERT INTO districts(id, name, state_id) VALUES (492, 'Gurdaspur', 18); 
INSERT INTO districts(id, name, state_id) VALUES (493, 'Hoshiarpur', 18); 
INSERT INTO districts(id, name, state_id) VALUES (494, 'Jalandhar', 18); 
INSERT INTO districts(id, name, state_id) VALUES (495, 'Kapurthala', 18); 
INSERT INTO districts(id, name, state_id) VALUES (496, 'Ludhiana', 18); 
INSERT INTO districts(id, name, state_id) VALUES (497, 'Mansa', 18); 
INSERT INTO districts(id, name, state_id) VALUES (498, 'Moga', 18); 
INSERT INTO districts(id, name, state_id) VALUES (499, 'Pathankot', 18); 
INSERT INTO districts(id, name, state_id) VALUES (500, 'Patiala', 18); 
INSERT INTO districts(id, name, state_id) VALUES (501, 'Rupnagar', 18); 
INSERT INTO districts(id, name, state_id) VALUES (502, 'S.A.S. Nagar', 18); 
INSERT INTO districts(id, name, state_id) VALUES (503, 'Sangrur', 18); 
INSERT INTO districts(id, name, state_id) VALUES (504, 'Shahid Bhagat Singh Nagar', 18); 
INSERT INTO districts(id, name, state_id) VALUES (505, 'Sri Muktsar Sahib', 18); 
INSERT INTO districts(id, name, state_id) VALUES (506, 'Tarn Taran', 18); 
INSERT INTO districts(id, name, state_id) VALUES (507, 'Karaikal', 6); 
INSERT INTO districts(id, name, state_id) VALUES (508, 'Mahe', 6); 
INSERT INTO districts(id, name, state_id) VALUES (509, 'Puducherry', 6); 
INSERT INTO districts(id, name, state_id) VALUES (510, 'Yanam', 6); 
INSERT INTO districts(id, name, state_id) VALUES (511, 'Ajmer', 9); 
INSERT INTO districts(id, name, state_id) VALUES (512, 'Alwar', 9); 
INSERT INTO districts(id, name, state_id) VALUES (513, 'Banswara', 9); 
INSERT INTO districts(id, name, state_id) VALUES (514, 'Baran', 9); 
INSERT INTO districts(id, name, state_id) VALUES (515, 'Barmer', 9); 
INSERT INTO districts(id, name, state_id) VALUES (516, 'Bharatpur', 9); 
INSERT INTO districts(id, name, state_id) VALUES (517, 'Bhilwara', 9); 
INSERT INTO districts(id, name, state_id) VALUES (518, 'Bikaner', 9); 
INSERT INTO districts(id, name, state_id) VALUES (519, 'Bundi', 9); 
INSERT INTO districts(id, name, state_id) VALUES (520, 'Chittorgarh', 9); 
INSERT INTO districts(id, name, state_id) VALUES (521, 'Churu', 9); 
INSERT INTO districts(id, name, state_id) VALUES (522, 'Dausa', 9); 
INSERT INTO districts(id, name, state_id) VALUES (523, 'Dholpur', 9); 
INSERT INTO districts(id, name, state_id) VALUES (524, 'Dungarpur', 9); 
INSERT INTO districts(id, name, state_id) VALUES (525, 'Ganganagar', 9); 
INSERT INTO districts(id, name, state_id) VALUES (526, 'Hanumangarh', 9); 
INSERT INTO districts(id, name, state_id) VALUES (527, 'Jaipur', 9); 
INSERT INTO districts(id, name, state_id) VALUES (528, 'Jaisalmer', 9); 
INSERT INTO districts(id, name, state_id) VALUES (529, 'Jalore', 9); 
INSERT INTO districts(id, name, state_id) VALUES (530, 'Jhalawar', 9); 
INSERT INTO districts(id, name, state_id) VALUES (531, 'Jhunjhunu', 9); 
INSERT INTO districts(id, name, state_id) VALUES (532, 'Jodhpur', 9); 
INSERT INTO districts(id, name, state_id) VALUES (533, 'Karauli', 9); 
INSERT INTO districts(id, name, state_id) VALUES (534, 'Kota', 9); 
INSERT INTO districts(id, name, state_id) VALUES (535, 'Nagaur', 9); 
INSERT INTO districts(id, name, state_id) VALUES (536, 'Pali', 9); 
INSERT INTO districts(id, name, state_id) VALUES (537, 'Pratapgarh', 9); 
INSERT INTO districts(id, name, state_id) VALUES (538, 'Rajsamand', 9); 
INSERT INTO districts(id, name, state_id) VALUES (539, 'Sawai Madhopur', 9); 
INSERT INTO districts(id, name, state_id) VALUES (540, 'Sikar', 9); 
INSERT INTO districts(id, name, state_id) VALUES (541, 'Sirohi', 9); 
INSERT INTO districts(id, name, state_id) VALUES (542, 'Tonk', 9); 
INSERT INTO districts(id, name, state_id) VALUES (543, 'Udaipur', 9); 
INSERT INTO districts(id, name, state_id) VALUES (544, 'East Sikkim', 28); 
INSERT INTO districts(id, name, state_id) VALUES (545, 'North Sikkim', 28); 
INSERT INTO districts(id, name, state_id) VALUES (546, 'South Sikkim', 28); 
INSERT INTO districts(id, name, state_id) VALUES (547, 'West Sikkim', 28); 
INSERT INTO districts(id, name, state_id) VALUES (548, 'Adilabad', 1); 
INSERT INTO districts(id, name, state_id) VALUES (549, 'Bhadradri Kothagudem', 1); 
INSERT INTO districts(id, name, state_id) VALUES (550, 'Hyderabad', 1); 
INSERT INTO districts(id, name, state_id) VALUES (551, 'Jagtial', 1); 
INSERT INTO districts(id, name, state_id) VALUES (552, 'Jangaon', 1); 
INSERT INTO districts(id, name, state_id) VALUES (553, 'Jayashankar Bhupalapally', 1); 
INSERT INTO districts(id, name, state_id) VALUES (554, 'Jogulamba Gadwal', 1); 
INSERT INTO districts(id, name, state_id) VALUES (555, 'Kamareddy', 1); 
INSERT INTO districts(id, name, state_id) VALUES (556, 'Karimnagar', 1); 
INSERT INTO districts(id, name, state_id) VALUES (557, 'Khammam', 1); 
INSERT INTO districts(id, name, state_id) VALUES (558, 'Komaram Bheem', 1); 
INSERT INTO districts(id, name, state_id) VALUES (559, 'Mahabubabad', 1); 
INSERT INTO districts(id, name, state_id) VALUES (560, 'Mahabubnagar', 1); 
INSERT INTO districts(id, name, state_id) VALUES (561, 'Mancherial', 1); 
INSERT INTO districts(id, name, state_id) VALUES (562, 'Medak', 1); 
INSERT INTO districts(id, name, state_id) VALUES (563, 'Medchal Malkajgiri', 1); 
INSERT INTO districts(id, name, state_id) VALUES (564, 'Mulugu', 1); 
INSERT INTO districts(id, name, state_id) VALUES (565, 'Nagarkurnool', 1); 
INSERT INTO districts(id, name, state_id) VALUES (566, 'Nalgonda', 1); 
INSERT INTO districts(id, name, state_id) VALUES (567, 'Narayanpet', 1); 
INSERT INTO districts(id, name, state_id) VALUES (568, 'Nirmal', 1); 
INSERT INTO districts(id, name, state_id) VALUES (569, 'Nizamabad', 1); 
INSERT INTO districts(id, name, state_id) VALUES (570, 'Peddapalli', 1); 
INSERT INTO districts(id, name, state_id) VALUES (571, 'Rajanna Sircilla', 1); 
INSERT INTO districts(id, name, state_id) VALUES (572, 'Ranga Reddy', 1); 
INSERT INTO districts(id, name, state_id) VALUES (573, 'Sangareddy', 1); 
INSERT INTO districts(id, name, state_id) VALUES (574, 'Siddipet', 1); 
INSERT INTO districts(id, name, state_id) VALUES (575, 'Suryapet', 1); 
INSERT INTO districts(id, name, state_id) VALUES (576, 'Vikarabad', 1); 
INSERT INTO districts(id, name, state_id) VALUES (577, 'Wanaparthy', 1); 
INSERT INTO districts(id, name, state_id) VALUES (578, 'Warangal Rural', 1); 
INSERT INTO districts(id, name, state_id) VALUES (579, 'Warangal Urban', 1); 
INSERT INTO districts(id, name, state_id) VALUES (580, 'Yadadri Bhuvanagiri', 1); 
INSERT INTO districts(id, name, state_id) VALUES (581, 'Ariyalur', 7); 
INSERT INTO districts(id, name, state_id) VALUES (582, 'Chennai', 7); 
INSERT INTO districts(id, name, state_id) VALUES (583, 'Coimbatore', 7); 
INSERT INTO districts(id, name, state_id) VALUES (584, 'Cuddalore', 7); 
INSERT INTO districts(id, name, state_id) VALUES (585, 'Dharmapuri', 7); 
INSERT INTO districts(id, name, state_id) VALUES (586, 'Dindigul', 7); 
INSERT INTO districts(id, name, state_id) VALUES (587, 'Erode', 7); 
INSERT INTO districts(id, name, state_id) VALUES (588, 'Kancheepuram', 7); 
INSERT INTO districts(id, name, state_id) VALUES (589, 'Kanyakumari', 7); 
INSERT INTO districts(id, name, state_id) VALUES (590, 'Karur', 7); 
INSERT INTO districts(id, name, state_id) VALUES (591, 'Krishnagiri', 7); 
INSERT INTO districts(id, name, state_id) VALUES (592, 'Madurai', 7); 
INSERT INTO districts(id, name, state_id) VALUES (593, 'Nagapattinam', 7); 
INSERT INTO districts(id, name, state_id) VALUES (594, 'Namakkal', 7); 
INSERT INTO districts(id, name, state_id) VALUES (595, 'Perambalur', 7); 
INSERT INTO districts(id, name, state_id) VALUES (596, 'Pudukkottai', 7); 
INSERT INTO districts(id, name, state_id) VALUES (597, 'Ramanathapuram', 7); 
INSERT INTO districts(id, name, state_id) VALUES (598, 'Salem', 7); 
INSERT INTO districts(id, name, state_id) VALUES (599, 'Sivaganga', 7); 
INSERT INTO districts(id, name, state_id) VALUES (600, 'Thanjavur', 7); 
INSERT INTO districts(id, name, state_id) VALUES (601, 'Nilgiris', 7); 
INSERT INTO districts(id, name, state_id) VALUES (602, 'Theni', 7); 
INSERT INTO districts(id, name, state_id) VALUES (603, 'Thiruvallur', 7); 
INSERT INTO districts(id, name, state_id) VALUES (604, 'Thiruvarur', 7); 
INSERT INTO districts(id, name, state_id) VALUES (605, 'Thoothukkudi', 7); 
INSERT INTO districts(id, name, state_id) VALUES (606, 'Tiruchirappalli', 7); 
INSERT INTO districts(id, name, state_id) VALUES (607, 'Tirunelveli', 7); 
INSERT INTO districts(id, name, state_id) VALUES (608, 'Tiruppur', 7); 
INSERT INTO districts(id, name, state_id) VALUES (609, 'Tiruvannamalai', 7); 
INSERT INTO districts(id, name, state_id) VALUES (610, 'Vellore', 7); 
INSERT INTO districts(id, name, state_id) VALUES (611, 'Viluppuram', 7); 
INSERT INTO districts(id, name, state_id) VALUES (612, 'Virudhunagar', 7); 
INSERT INTO districts(id, name, state_id) VALUES (613, 'Tenkasi', 7); 
INSERT INTO districts(id, name, state_id) VALUES (614, 'Chengalpattu', 7); 
INSERT INTO districts(id, name, state_id) VALUES (615, 'Ranipet', 7); 
INSERT INTO districts(id, name, state_id) VALUES (616, 'Kallakurichi', 7); 
INSERT INTO districts(id, name, state_id) VALUES (617, 'Tirupathur', 7); 
INSERT INTO districts(id, name, state_id) VALUES (618, 'Dhalai', 2); 
INSERT INTO districts(id, name, state_id) VALUES (619, 'Gomati', 2); 
INSERT INTO districts(id, name, state_id) VALUES (620, 'Khowai', 2); 
INSERT INTO districts(id, name, state_id) VALUES (621, 'North Tripura', 2); 
INSERT INTO districts(id, name, state_id) VALUES (622, 'Sipahijala', 2); 
INSERT INTO districts(id, name, state_id) VALUES (623, 'South Tripura', 2); 
INSERT INTO districts(id, name, state_id) VALUES (624, 'Unokoti', 2); 
INSERT INTO districts(id, name, state_id) VALUES (625, 'West Tripura', 2); 
INSERT INTO districts(id, name, state_id) VALUES (626, 'Agra', 12); 
INSERT INTO districts(id, name, state_id) VALUES (627, 'Aligarh', 12); 
INSERT INTO districts(id, name, state_id) VALUES (628, 'Ambedkar Nagar', 12); 
INSERT INTO districts(id, name, state_id) VALUES (629, 'Amethi', 12); 
INSERT INTO districts(id, name, state_id) VALUES (630, 'Amroha', 12); 
INSERT INTO districts(id, name, state_id) VALUES (631, 'Auraiya', 12); 
INSERT INTO districts(id, name, state_id) VALUES (632, 'Azamgarh', 12); 
INSERT INTO districts(id, name, state_id) VALUES (633, 'Baghpat', 12); 
INSERT INTO districts(id, name, state_id) VALUES (634, 'Bahraich', 12); 
INSERT INTO districts(id, name, state_id) VALUES (635, 'Ballia', 12); 
INSERT INTO districts(id, name, state_id) VALUES (636, 'Balrampur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (637, 'Banda', 12); 
INSERT INTO districts(id, name, state_id) VALUES (638, 'Barabanki', 12); 
INSERT INTO districts(id, name, state_id) VALUES (639, 'Bareilly', 12); 
INSERT INTO districts(id, name, state_id) VALUES (640, 'Basti', 12); 
INSERT INTO districts(id, name, state_id) VALUES (641, 'Bhadohi', 12); 
INSERT INTO districts(id, name, state_id) VALUES (642, 'Bijnor', 12); 
INSERT INTO districts(id, name, state_id) VALUES (643, 'Budaun', 12); 
INSERT INTO districts(id, name, state_id) VALUES (644, 'Bulandshahr', 12); 
INSERT INTO districts(id, name, state_id) VALUES (645, 'Chandauli', 12); 
INSERT INTO districts(id, name, state_id) VALUES (646, 'Chitrakoot', 12); 
INSERT INTO districts(id, name, state_id) VALUES (647, 'Deoria', 12); 
INSERT INTO districts(id, name, state_id) VALUES (648, 'Etah', 12); 
INSERT INTO districts(id, name, state_id) VALUES (649, 'Etawah', 12); 
INSERT INTO districts(id, name, state_id) VALUES (650, 'Farrukhabad', 12); 
INSERT INTO districts(id, name, state_id) VALUES (651, 'Fatehpur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (652, 'Firozabad', 12); 
INSERT INTO districts(id, name, state_id) VALUES (653, 'Gautam Buddha Nagar', 12); 
INSERT INTO districts(id, name, state_id) VALUES (654, 'Ghaziabad', 12); 
INSERT INTO districts(id, name, state_id) VALUES (655, 'Ghazipur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (656, 'Gonda', 12); 
INSERT INTO districts(id, name, state_id) VALUES (657, 'Gorakhpur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (658, 'Hamirpur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (659, 'Hapur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (660, 'Hardoi', 12); 
INSERT INTO districts(id, name, state_id) VALUES (661, 'Hathras', 12); 
INSERT INTO districts(id, name, state_id) VALUES (662, 'Jalaun', 12); 
INSERT INTO districts(id, name, state_id) VALUES (663, 'Jaunpur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (664, 'Jhansi', 12); 
INSERT INTO districts(id, name, state_id) VALUES (665, 'Kannauj', 12); 
INSERT INTO districts(id, name, state_id) VALUES (666, 'Kanpur Dehat', 12); 
INSERT INTO districts(id, name, state_id) VALUES (667, 'Kanpur Nagar', 12); 
INSERT INTO districts(id, name, state_id) VALUES (668, 'Kasganj', 12); 
INSERT INTO districts(id, name, state_id) VALUES (669, 'Kaushambi', 12); 
INSERT INTO districts(id, name, state_id) VALUES (670, 'Lakhimpur Kheri', 12); 
INSERT INTO districts(id, name, state_id) VALUES (671, 'Kushinagar', 12); 
INSERT INTO districts(id, name, state_id) VALUES (672, 'Lalitpur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (673, 'Lucknow', 12); 
INSERT INTO districts(id, name, state_id) VALUES (674, 'Mahoba', 12); 
INSERT INTO districts(id, name, state_id) VALUES (675, 'Maharajganj', 12); 
INSERT INTO districts(id, name, state_id) VALUES (676, 'Mainpuri', 12); 
INSERT INTO districts(id, name, state_id) VALUES (677, 'Mathura', 12); 
INSERT INTO districts(id, name, state_id) VALUES (678, 'Mau', 12); 
INSERT INTO districts(id, name, state_id) VALUES (679, 'Meerut', 12); 
INSERT INTO districts(id, name, state_id) VALUES (680, 'Mirzapur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (681, 'Moradabad', 12); 
INSERT INTO districts(id, name, state_id) VALUES (682, 'Muzaffarnagar', 12); 
INSERT INTO districts(id, name, state_id) VALUES (683, 'Pilibhit', 12); 
INSERT INTO districts(id, name, state_id) VALUES (684, 'Pratapgarh', 12); 
INSERT INTO districts(id, name, state_id) VALUES (685, 'Prayagraj', 12); 
INSERT INTO districts(id, name, state_id) VALUES (686, 'Rae Bareli', 12); 
INSERT INTO districts(id, name, state_id) VALUES (687, 'Rampur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (688, 'Saharanpur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (689, 'Sambhal', 12); 
INSERT INTO districts(id, name, state_id) VALUES (690, 'Sant Kabir Nagar', 12); 
INSERT INTO districts(id, name, state_id) VALUES (691, 'Shahjahanpur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (692, 'Shamli', 12); 
INSERT INTO districts(id, name, state_id) VALUES (693, 'Shrawasti', 12); 
INSERT INTO districts(id, name, state_id) VALUES (694, 'Siddharthnagar', 12); 
INSERT INTO districts(id, name, state_id) VALUES (695, 'Sitapur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (696, 'Sonbhadra', 12); 
INSERT INTO districts(id, name, state_id) VALUES (697, 'Sultanpur', 12); 
INSERT INTO districts(id, name, state_id) VALUES (698, 'Unnao', 12); 
INSERT INTO districts(id, name, state_id) VALUES (699, 'Varanasi', 12); 
INSERT INTO districts(id, name, state_id) VALUES (700, 'Ayodhya', 12); 
INSERT INTO districts(id, name, state_id) VALUES (701, 'Almora', 25); 
INSERT INTO districts(id, name, state_id) VALUES (702, 'Bageshwar', 25); 
INSERT INTO districts(id, name, state_id) VALUES (703, 'Chamoli', 25); 
INSERT INTO districts(id, name, state_id) VALUES (704, 'Champawat', 25); 
INSERT INTO districts(id, name, state_id) VALUES (705, 'Dehradun', 25); 
INSERT INTO districts(id, name, state_id) VALUES (706, 'Haridwar', 25); 
INSERT INTO districts(id, name, state_id) VALUES (707, 'Nainital', 25); 
INSERT INTO districts(id, name, state_id) VALUES (708, 'Pauri Garhwal', 25); 
INSERT INTO districts(id, name, state_id) VALUES (709, 'Pithoragarh', 25); 
INSERT INTO districts(id, name, state_id) VALUES (710, 'Rudraprayag', 25); 
INSERT INTO districts(id, name, state_id) VALUES (711, 'Tehri Garhwal', 25); 
INSERT INTO districts(id, name, state_id) VALUES (712, 'Udham Singh Nagar', 25); 
INSERT INTO districts(id, name, state_id) VALUES (713, 'Uttarkashi', 25); 
INSERT INTO districts(id, name, state_id) VALUES (714, 'Alipurduar', 19); 
INSERT INTO districts(id, name, state_id) VALUES (715, 'Bankura', 19); 
INSERT INTO districts(id, name, state_id) VALUES (716, 'Birbhum', 19); 
INSERT INTO districts(id, name, state_id) VALUES (717, 'Cooch Behar', 19); 
INSERT INTO districts(id, name, state_id) VALUES (718, 'Dakshin Dinajpur', 19); 
INSERT INTO districts(id, name, state_id) VALUES (719, 'Darjeeling', 19); 
INSERT INTO districts(id, name, state_id) VALUES (720, 'Hooghly', 19); 
INSERT INTO districts(id, name, state_id) VALUES (721, 'Howrah', 19); 
INSERT INTO districts(id, name, state_id) VALUES (722, 'Jalpaiguri', 19); 
INSERT INTO districts(id, name, state_id) VALUES (723, 'Jhargram', 19); 
INSERT INTO districts(id, name, state_id) VALUES (724, 'Kalimpong', 19); 
INSERT INTO districts(id, name, state_id) VALUES (725, 'Kolkata', 19); 
INSERT INTO districts(id, name, state_id) VALUES (726, 'Malda', 19); 
INSERT INTO districts(id, name, state_id) VALUES (727, 'Paschim Medinipur', 19); 
INSERT INTO districts(id, name, state_id) VALUES (728, 'Murshidabad', 19); 
INSERT INTO districts(id, name, state_id) VALUES (729, 'Nadia', 19); 
INSERT INTO districts(id, name, state_id) VALUES (730, 'North 24 Parganas', 19); 
INSERT INTO districts(id, name, state_id) VALUES (731, 'Paschim Bardhaman', 19); 
INSERT INTO districts(id, name, state_id) VALUES (732, 'Purba Bardhaman', 19); 
INSERT INTO districts(id, name, state_id) VALUES (733, 'Purba Medinipur', 19); 
INSERT INTO districts(id, name, state_id) VALUES (734, 'Purulia', 19); 
INSERT INTO districts(id, name, state_id) VALUES (735, 'South 24 Parganas', 19); 
INSERT INTO districts(id, name, state_id) VALUES (736, 'Uttar Dinajpur', 19); 
